[build]
  publish="dist"
  command="gridsome build"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "netlify-plugin-a11y"

[[plugins]]
  package = "netlify-plugin-gridsome-cache"

[[plugins]]
package = "netlify-plugin-checklinks"